//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDeneyimlerim> TBLDeneyimlerim { get; set; }
        public virtual DbSet<TBLEgitimlerim> TBLEgitimlerim { get; set; }
        public virtual DbSet<TBLHakkimda> TBLHakkimda { get; set; }
        public virtual DbSet<TBLHobilerim> TBLHobilerim { get; set; }
        public virtual DbSet<TBLİletisim> TBLİletisim { get; set; }
        public virtual DbSet<TBLSertifikalarim> TBLSertifikalarim { get; set; }
        public virtual DbSet<TBLYeteneklerim> TBLYeteneklerim { get; set; }
    }
}
